[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["openzeppelin/=lib/openzeppelin-contracts/", "ethos/=src/"]

[rpc_endpoints]
optimism = "${OPTIMISM_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
celo = "${CELO_RPC_URL}"
celo_alfajores = "${CELO_ALFAJORES_RPC_URL}"

[etherscan]
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }
optimism_sepolia = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", url = "https://api-sepolia-optimistic.etherscan.io/api" }
celo = { key = "${CELO_ETHERSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
celo_alfajores = { key = "${CELO_ETHERSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
